import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Inter"', '"SF Pro Display"', '-apple-system', 'system-ui', '"Segoe UI"', 'Roboto', 'sans-serif'],
        mono: ['"Berkeley Mono"', '"SFMono Regular"', 'Consolas', '"Liberation Mono"', 'Menlo', 'Courier', 'monospace'],
      },
      fontSize: {
        'xs': ['11px', { lineHeight: '1.4' }],
        'sm': ['12px', { lineHeight: '1.4' }],
        'base': ['13px', { lineHeight: '1.4' }],
        'md': ['14px', { lineHeight: '1.4' }],
        'lg': ['16px', { lineHeight: '1.2' }],
        'xl': ['18px', { lineHeight: '1.2' }],
        '2xl': ['20px', { lineHeight: '1.2' }],
        '3xl': ['24px', { lineHeight: '1.2' }],
      },
      spacing: {
        '0.5': '2px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        '2.5': '10px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        'sidebar': '244px',
      },
      borderRadius: {
        'none': '0px',
        'sm': '2px',
        DEFAULT: '4px',
        'md': '6px',
        'lg': '8px',
        'xl': '12px',
        'full': '9999px',
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        linear: {
          sidebar: '#090909',
          base: '#101012',
          card: '#17181a',
          hover: '#1e2024',
          border: '#23252a',
          purple: '#5e6ad2',
          'purple-hover': '#6c77db',
          'text-primary': '#ffffff',
          'text-secondary': '#6b6f76',
          'text-tertiary': '#545760',
          success: '#59a200',
          warning: '#f2c94c',
          error: '#eb5757',
          info: '#2f80ed',
        },
        status: {
          backlog: '#95979d',
          todo: '#e8e8e8',
          'in-progress': '#f2c94c',
          'in-review': '#f2c94c',
          done: '#5e6ad2',
          canceled: '#95979d',
          duplicate: '#95979d',
        },
        priority: {
          urgent: '#eb5757',
          high: '#f2994a',
          medium: '#f2c94c',
          low: '#6fcf97',
          none: '#95979d',
        },
        label: {
          red: '#eb5757',
          orange: '#f2994a',
          yellow: '#f2c94c',
          green: '#6fcf97',
          teal: '#56ccf2',
          blue: '#2f80ed',
          purple: '#9b51e0',
          pink: '#f178b6',
        },
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      boxShadow: {
        'linear-sm': '0 1px 2px rgba(0, 0, 0, 0.3)',
        'linear': '0 2px 4px rgba(0, 0, 0, 0.3)',
        'linear-md': '0 4px 8px rgba(0, 0, 0, 0.3)',
        'linear-lg': '0 8px 16px rgba(0, 0, 0, 0.4)',
        'linear-modal': '0 16px 48px rgba(0, 0, 0, 0.5)',
      },
      transitionDuration: {
        'fast': '150ms',
        DEFAULT: '200ms',
        'slow': '300ms',
      },
      transitionTimingFunction: {
        DEFAULT: 'ease-out',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "pulse-subtle": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "pulse-subtle": "pulse-subtle 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
